---
- block:
  - name: install scm packages
    apt: "name={{ item }}  state=latest"
    with_items:
      - mercurial
      - git
  - name: get root of base dir
    shell: "dirname {{ python_wsgiapp_basedir }}"
    register: root_dir
  - name: create root of base dir
    file: "path={{ root_dir.stdout }} state=directory mode=0755"
  - name: add github and bitbucket to ssh known hosts
    script: "add_ssh_known_hosts.sh"
  - name: checkout source code via scm
    command: "{{ python_wsgiapp_scm }} clone {{ python_wsgiapp_repo }} {{ python_wsgiapp_basedir }}"
  - name: create virtualenv under the project directory
    command: "python3 -m venv {{ python_wsgiapp_basedir }}/.venv"
  - name: install pipenv package
    command: "{{ python_wsgiapp_basedir }}/.venv/bin/pip install pipenv"
  - name: install project dependency packages
    command: "{{ python_wsgiapp_basedir }}/.venv/bin/pipenv sync"
    args:
      chdir: "{{ python_wsgiapp_basedir }}"
  - name: install project
    command: "{{ python_wsgiapp_basedir }}/.venv/bin/pip install -e ."
    args:
      chdir: "{{ python_wsgiapp_basedir }}"
  - name: fetch cpu count
    shell: "cat /proc/cpuinfo | grep ^processor | wc -l"
    register: cpu_count
  - name: setup wsgi configuration of the project
    copy:
      remote_src: "yes"
      src: "{{ python_wsgiapp_basedir }}/wsgi.py.sample"
      dest: "{{ python_wsgiapp_basedir }}/wsgi.py"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: install uwsgi configuration of the project
    template:
      src: "uwsgi.ini.j2"
      dest: "/opt/uwsgi/etc/{{ python_wsgiapp_domain_name }}.ini" 
  tags:
    - python_wsgiapp
