---
- block:
  - name: install scm packages
    apt: "name={{ packages }}  state=latest"
    vars:
      packages:
        - mercurial
        - git

  - name: create web root dir
    file:
      path: "{{ python_wsgiapp_web_base_dir }}"
      state: "directory"
      mode: "0711"
      owner: "root"
      group: "root"

  - name: get root of base dir
    shell: "dirname {{ item.base_dir }}"
    register: base_dirs
    loop: "{{ python_wsgiapp_vars }}"

  - name: create root of base dir
    file: "path={{ item.stdout }} state=directory mode=0755"
    loop: "{{ base_dirs.results }}"

  - name: add github and bitbucket to ssh known hosts
    script: "add_ssh_known_hosts.sh"

  - name: checkout source code via scm
    command: "{{ item.scm }} clone {{ item.repo_url }} {{ item.base_dir }}"
    args:
      creates: "{{ item.base_dir }}"
    loop: "{{ python_wsgiapp_vars }}"

  - name: create virtualenv under the project directory
    command: "python3 -m venv {{ item.base_dir }}/.venv"
    loop: "{{ python_wsgiapp_vars }}"

  - name: install pipenv package
    command: "{{ item.base_dir }}/.venv/bin/pip install pipenv"
    loop: "{{ python_wsgiapp_vars }}"

  - name: install project dependency packages
    command: "{{ item.base_dir }}/.venv/bin/pipenv sync"
    args:
      chdir: "{{ item.base_dir }}"
    loop: "{{ python_wsgiapp_vars }}"

  - name: install project
    command: "{{ item.base_dir }}/.venv/bin/pip install -e ."
    args:
      chdir: "{{ item.base_dir }}"
    loop: "{{ python_wsgiapp_vars }}"

  - name: fetch cpu count
    shell: "cat /proc/cpuinfo | grep ^processor | wc -l"
    register: cpu_count

  - name: setup wsgi configuration of the project
    copy:
      remote_src: "yes"
      src: "{{ item.base_dir }}/wsgi.py.sample"
      dest: "{{ item.base_dir }}/wsgi.py"
      owner: "root"
      group: "root"
      mode: "0644"
    loop: "{{ python_wsgiapp_vars }}"

  - name: install uwsgi configuration of the project
    template:
      src: "uwsgi.ini.j2"
      dest: "/opt/uwsgi/etc/{{ item.domain_name }}.ini" 
    loop: "{{ python_wsgiapp_vars }}"
  tags:
    - python_wsgiapp
