---
- block:
  - name: install scm packages
    ansible.builtin.apt: "name={{ packages }} state=latest"
    vars:
      packages:
        - git

  - name: create web root dir
    ansible.builtin.file:
      path: "{{ python_wsgiapps_web_base_dir }}"
      state: "directory"
      mode: "0711"
      owner: "root"
      group: "root"

  - name: get root of base dirs
    ansible.builtin.shell: "dirname {{ item.base_dir }}"
    register: base_dirs
    loop: "{{ python_wsgiapps }}"

  - name: checkout source code via scm
    ansible.builtin.command: "{{ item.scm }} clone {{ item.repo_url }} {{ item.base_dir }}"
    args:
      creates: "{{ item.base_dir }}"
    loop: "{{ python_wsgiapps }}"

  - name: create virtualenv under the project directory
    ansible.builtin.command: "python3 -m venv {{ item.base_dir }}/.venv"
    loop: "{{ python_wsgiapps }}"

  - name: install poetry package
    ansible.builtin.command: "{{ item.base_dir }}/.venv/bin/pip install poetry"
    loop: "{{ python_wsgiapps }}"

  - name: install project dependency packages
    ansible.builtin.command: "{{ item.base_dir }}/.venv/bin/poetry install --no-dev"
    args:
      chdir: "{{ item.base_dir }}"
    loop: "{{ python_wsgiapps }}"

  - name: fetch cpu count
    ansible.builtin.shell: "cat /proc/cpuinfo | grep ^processor | wc -l"
    register: cpu_count

  - name: setup wsgi configuration of the project
    ansible.builtin.copy:
      remote_src: "yes"
      src: "{{ item.base_dir }}/wsgi.py.sample"
      dest: "{{ item.base_dir }}/wsgi.py"
      owner: "root"
      group: "root"
      mode: "0644"
    loop: "{{ python_wsgiapps }}"

  - name: install uwsgi configuration of the project
    ansible.builtin.template:
      src: "uwsgi.ini.j2"
      dest: "/opt/uwsgi/etc/{{ item.domain_name }}.ini" 
    loop: "{{ python_wsgiapps }}"

  - name: restart uwsgi
    ansible.builtin.systemd:
      name: uwsgi
      state: restarted

  rescue:
  - name: remove web base dir if exists
    ansible.builtin.file:
      path: "{{ python_wsgiapps_web_base_dir }}"
      state: "absent"
  - name: error captured
    ansible.builtin.fail:
      msg: "Huston we have a problem."

  tags:
    - python_wsgiapps
